# Generated by Django 4.2.13 on 2024-05-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_filterstudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterStudents',
        ),
    ]
